## $ID: reading_TIF.R, last updated 2018/12/07, F. Osorio

# to load images in TIF format
library(tiff)
synthetic00 <- readTIFF("../data/synthetic00.tif")
synthetic10 <- readTIFF("../data/synthetic10.tif")
synthetic15 <- readTIFF("../data/synthetic15.tif")
synthetic1R <- readTIFF("../data/synthetic1R.tif")
synthetic40 <- readTIFF("../data/synthetic40.tif")
synthetic45 <- readTIFF("../data/synthetic45.tif")
synthetic4R <- readTIFF("../data/synthetic4R.tif")
synthetic80 <- readTIFF("../data/synthetic80.tif")
synthetic85 <- readTIFF("../data/synthetic85.tif")
synthetic8R <- readTIFF("../data/synthetic8R.tif")

# scaling images to be in the interval [0,255]
synthetic00 <- round(255 * synthetic00)
synthetic10 <- round(255 * synthetic10)
synthetic15 <- round(255 * synthetic15)
synthetic1R <- round(255 * synthetic1R)
synthetic40 <- round(255 * synthetic40)
synthetic45 <- round(255 * synthetic45)
synthetic4R <- round(255 * synthetic4R)
synthetic80 <- round(255 * synthetic80)
synthetic85 <- round(255 * synthetic85)
synthetic8R <- round(255 * synthetic8R)

# rotating to natural order when plotted with 'image'
rows <- 1:512
cols <- 1:512
synthetic00 <- t(synthetic00[rev(rows),cols])
synthetic00 <- t(synthetic10[rev(rows),cols])
synthetic00 <- t(synthetic15[rev(rows),cols])
synthetic00 <- t(synthetic1R[rev(rows),cols])
synthetic00 <- t(synthetic40[rev(rows),cols])
synthetic00 <- t(synthetic45[rev(rows),cols])
synthetic00 <- t(synthetic4R[rev(rows),cols])
synthetic00 <- t(synthetic80[rev(rows),cols])
synthetic00 <- t(synthetic85[rev(rows),cols])
synthetic00 <- t(synthetic8R[rev(rows),cols])

# plotting in grayscale (lengthy operation)
image(synthetic00, col = gray((0:32)/32), axes = FALSE)
image(synthetic10, col = gray((0:32)/32), axes = FALSE)
image(synthetic15, col = gray((0:32)/32), axes = FALSE)
image(synthetic1R, col = gray((0:32)/32), axes = FALSE)
image(synthetic40, col = gray((0:32)/32), axes = FALSE)
image(synthetic45, col = gray((0:32)/32), axes = FALSE)
image(synthetic4R, col = gray((0:32)/32), axes = FALSE)
image(synthetic80, col = gray((0:32)/32), axes = FALSE)
image(synthetic85, col = gray((0:32)/32), axes = FALSE)
image(synthetic8R, col = gray((0:32)/32), axes = FALSE)

# saving images in R format (.rda)
save(synthetic00, file = "synthetic00.rda")
save(synthetic10, file = "synthetic10.rda")
save(synthetic15, file = "synthetic15.rda")
save(synthetic1R, file = "synthetic1R.rda")
save(synthetic40, file = "synthetic40.rda")
save(synthetic45, file = "synthetic45.rda")
save(synthetic4R, file = "synthetic4R.rda")
save(synthetic80, file = "synthetic80.rda")
save(synthetic85, file = "synthetic85.rda")
save(synthetic8R, file = "synthetic8R.rda")
